### ISSUE TITLE
Entity name in dataset

### ISSUE THREAD

**Issue by nhatminh-96** [qizhyuan/PRASE-Python#3]
Hello,

I have found in your dataset that you was able to crawl all entity names in OpenEA dataset, so that you can use name comparison as a baseline i.e STR-Match and EMB-Match. As DBPedia, YAGO and Wikipedia versions have changed through out the time, it was hard for me to crawl exactly the name of all entities in the OpenEA dataset. Would you kindly provide me the datasets in OpenEA that you have augmented with entity name please? Really appreciate you work!

Wish to hear from you,
Minh

**Comment by qizhyuan** [comment]
Hi,

Thanks for your question. 

I am sorry that I cannot provide you with the datasets since this work was conducted during my intern and I didn’t keep a copy of the preprocessed data with entity names. 

If I remember correctly, for Wikidata, we use the attribute value of an entity under http://www.wikidata.org/entity/P373 as its entity name. For DBpedia, we use the attribute value under http://dbpedia.org/ontology/name. And for YAGO, we use the attribute value under skos:prefLabel. These values might be further processed to get the final entity names. 

To help crawl the name of entities, I recommend that you use the online entity alignment demo PRASEMap https://prasemap.qizhy.com/. You can find the appropriate attributes corresponding to the entity names under the Visualization page after uploading your own KGs and running the alignment task.

Hope this will help!

**Comment by nhatminh-96** [comment]
Thanks alot!
